### ISSUE TITLE
Update der URL

### ISSUE THREAD

**Issue by mheumann** [Allergeeks/Web-Application#10]
Die URL sollte angepasst werden, ob man sich bei den Blacklisteinstellungen, oder Profileinstellungen befindet.
Außerdem den Title anpassen

**Comment by hendrikniemann** [comment]
Funtioniert nicht, sondern sorgt dafür, dass die App nicht mehr benutzbar ist, wenn sie in einem Unterordner sitzt, zB. `localhost/edible/`.

**Comment by morbaes** [comment]
In 2a4246fc2d518c546cfff440c1ca66dec3e81445 gefixt.
