### ISSUE TITLE
Filter funktionieren nicht

### ISSUE THREAD

**Issue by mheumann** [Allergeeks/Web-Application#13]
**Vorraussetzung:** Importieren von MarcoS Daten

Die Kategorie-Filter funktionieren nicht. Wenn nach "Nüssen" gefiltert wird kommen nicht alle Zutaten, die in der Kategorie "Nüsse" sind.
Wenn man "Laktose" filtert kommt keine von beiden Zutaten.

Der API-Call _http://dev.allergeeks.de/api/v1/ingredient/_ gibt als Response zu keiner Zutat eine Kategorie an.

**Comment by morbaes** [comment]
Älteres Datenmodell wurde verwende, Tabelle war falsch benannt.
